name: main branch

on:
    push:
        branches: [main]

jobs:
    publish_to_github_package_registry:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 14.x

            # TODO: consider npm ci instead
            - run: npm install

            - name: Semantic release
              run: npx semantic-release -b main -p @semantic-release/commit-analyzer -p @semantic-release/github -p @semantic-release/release-notes-generator -p @semantic-release/npm
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
